import React from 'react';
import {
  ArrowRight, BookOpen, CheckCircle2, ChevronRight, Download, FileCheck2,
  FileText, Grid3X3, Layers3, PanelsTopLeft, Ruler, ShieldCheck,
  Volume2, DraftingCompass, Wrench, Image as ImageIcon, Box, Building2,
  ClipboardList, Database, FileCode2, SwatchBook
} from 'lucide-react';

type System = {
  slug:string; title:string; short:string; intro:string; applications:string[];
  learn:string[]; manufacturer:string[]; docs:string[]; Icon:any;
};

const systems:System[] = [
  {slug:'linear-wood',title:'Linear Wood Ceilings',short:'Warm architectural rhythm with acoustic and service-integration options.',intro:'Linear wood ceilings use slats, planks or veneered modules to create continuous directional texture. ACUSTIQ will compare attachment methods, backing, acoustics, finishes, access and coordination requirements.',applications:['Corporate & workplace','Hospitality','Civic & cultural','Higher education'],learn:['Solid wood vs veneer vs wood-look systems','Open-joint vs closed-joint assemblies','Acoustic backing and NRC considerations','Suspension, access and service integration'],manufacturer:['Product family names and one-line positioning','Species / veneer / laminate / finish options','Module dimensions, slat widths and spacing','Acoustic configurations and verified NRC data','Fire performance and test references','Suspension / carrier details and perimeter conditions'],docs:['Data sheets','Installation manual','CAD details','BIM/Revit files','Finish cards','Warranty'],Icon:PanelsTopLeft},
  {slug:'linear-metal',title:'Linear Metal Ceilings',short:'Durable, precise systems for commercial and institutional interiors.',intro:'Linear metal ceilings include pans, planks, strips and carrier-supported systems. The key specification questions are module geometry, perforation, acoustic infill, access, corrosion resistance and suspension.',applications:['Transit & infrastructure','Retail','Healthcare','Commercial interiors'],learn:['Panel and carrier types','Perforated vs non-perforated metal','Acoustic infill strategies','Exterior / high-humidity considerations'],manufacturer:['Exact panel profiles and module sizes','Metal gauge / alloy and coating system','Standard and custom colours','Perforation patterns and open area','Acoustic backing options','Exterior/interior suitability and limitations'],docs:['Technical data','Finish chart','Installation guide','CAD details','BIM objects','Cleaning & maintenance'],Icon:Layers3},
  {slug:'acoustic-baffles',title:'Acoustic Baffles',short:'Vertical absorptive elements for open-plenum spaces and expressive acoustics.',intro:'Baffles increase absorptive surface area while keeping structure and services visible. Good specification content needs spacing, suspension, material, fire performance, acoustics and coordination rules.',applications:['Open offices','Recreation','Education','Restaurants'],learn:['Baffle spacing and visual density','Sabins vs NRC for free-hanging absorbers','PET, mineral fibre and fabric systems','Sprinkler, lighting and diffuser coordination'],manufacturer:['Available shapes, sizes and thicknesses','Material composition and recycled content','Verified acoustic test data','Fire classification / test report references','Suspension hardware and maximum drops','Colours and custom printing / cutting options'],docs:['Acoustic reports','Fire reports','Suspension details','CAD/BIM','Colour chart','Care instructions'],Icon:Volume2},
  {slug:'open-cell',title:'Open Cell Ceilings',short:'Modular visual screening with continued access to the plenum.',intro:'Open-cell systems create a ceiling plane without fully closing the plenum. Specification depends on cell module, blade depth, material, colour, carrier geometry, access and service visibility.',applications:['Retail','Airports','Food halls','Large public spaces'],learn:['Cell size and visual screening','Carrier and module layouts','Lighting and sprinkler coordination','Access and maintenance strategy'],manufacturer:['Cell modules and blade depths','Panel/module dimensions','Material and finish system','Suspension grid / carrier layout','Access method and service integration notes','Interior/exterior limitations'],docs:['System data sheet','Reflected ceiling details','Installation guide','CAD/BIM','Colour chart','Warranty'],Icon:Grid3X3},
  {slug:'acoustic-clouds',title:'Acoustic Clouds',short:'Suspended absorptive elements for targeted reverberation control.',intro:'Clouds can be flat, shaped, framed or frameless. ACUSTIQ will document mounting heights, suspension, acoustic performance, edge options, shapes and spacing so designers can move from concept to specification.',applications:['Boardrooms','Schools','Lobbies','Studios'],learn:['Cloud placement and acoustic coverage','Free-hanging absorber performance','Shapes, edges and custom geometry','Coordination above occupied zones'],manufacturer:['Standard shapes and dimensions','Thicknesses and edge treatments','Verified acoustic data / sabins per unit','Suspension hardware and allowable cable lengths','Colours / fabrics / prints','Seismic and restraint guidance where applicable'],docs:['Acoustic test report','Fire report','Suspension guide','CAD/BIM','Finish chart','Cleaning instructions'],Icon:DraftingCompass},
  {slug:'suspended-tbar',title:'Suspended T-Bar Ceilings',short:'The commercial ceiling workhorse: grid, panels, access and coordination.',intro:'Suspended T-bar ceilings combine exposed suspension grid with lay-in or tegular panels. ACUSTIQ will organize grid geometry, panel edge, seismic restraint, fixture support and integration with MEP services.',applications:['Offices','Schools','Healthcare','Tenant improvements'],learn:['15/16 in vs 9/16 in grid','Square lay-in vs tegular edges','Hanger, perimeter and fixture coordination','Seismic categories and bracing concepts'],manufacturer:['Grid family and duty classification','Main/cross tee dimensions and face widths','Panel families compatible with each grid','Load data and hanger requirements','Seismic component details','Corrosion-resistant / cleanroom options'],docs:['Grid data sheets','Panel data sheets','Seismic details','Installation manual','CAD/BIM','Certificates / listings'],Icon:FileCheck2},
  {slug:'specialty',title:'Specialty & Custom Ceilings',short:'Custom forms, islands, canopies and integrated architectural assemblies.',intro:'Specialty ceilings often combine several materials and trades. This area will showcase custom-engineered assemblies, integrated lighting, feature ceilings and unusual geometries once verified project information is available.',applications:['Feature lobbies','Museums','Hospitality','Flagship retail'],learn:['Custom engineering workflow','Mockups and shop drawings','Integration with lighting and mechanical','Access, tolerances and sequencing'],manufacturer:['Capabilities and fabrication limits','Materials and finish library','Engineering / shop drawing support','Typical lead times and mockup process','Maximum module sizes and tolerances','Real completed project examples'],docs:['Capability brochure','Typical details','Material samples','Project case studies','Shop drawing examples','Warranty'],Icon:Box}
];

const resources = [
  ['NRC, CAC & STC Explained','Understand what each acoustic rating measures and when it matters.',Volume2],
  ['Suspended Ceiling Components','Main tees, cross tees, wall angle, hanger wire, clips and panels.',Layers3],
  ['Seismic Ceiling Fundamentals','A practical overview of bracing, perimeter conditions and coordination.',ShieldCheck],
  ['Ceiling Takeoff & Estimating','How to think about grid, panels, perimeter, waste and accessories.',Ruler],
  ['Lighting / HVAC / Sprinklers','Coordinate the ceiling plane with the services that penetrate it.',Building2],
  ['NMS / Specification Framework','Map system information into Canadian master-specification language.',FileText]
];

function currentPath(){ return window.location.pathname.replace(/\/+$/,'') || '/'; }
function go(path:string){ window.history.pushState({},'',path); window.dispatchEvent(new PopStateEvent('popstate')); window.scrollTo({top:0,behavior:'smooth'}); }
function A({to,children,className=''}:{to:string;children:React.ReactNode;className?:string}){return <a href={to} className={className} onClick={e=>{e.preventDefault();go(to)}}>{children}</a>}

function Header(){return <header className="topbar"><A to="/" className="brand">ACUSTIQ<span>.</span></A><nav><A to="/systems">Systems</A><A to="/products">Products</A><A to="/technical-library">Technical Library</A><A to="/for-matt">Content Map</A></nav><A to="/for-matt" className="top-cta">Manufacturer Upload Map</A></header>}
function Footer(){return <footer><b>ACUSTIQ.</b><span>Architectural Ceiling Systems & Acoustic Design</span><span>Canada · Manufacturer data published from verified source material</span></footer>}

function ConceptVisual({variant='wood'}:{variant?:string}){return <div className={`concept concept-${variant}`}><div className="concept-grid">{Array.from({length:14}).map((_,i)=><i key={i}/>)}</div><div className="concept-label">CONCEPT VISUAL · REPLACE WITH VERIFIED PROJECT PHOTOGRAPHY</div></div>}

function Home(){return <>
<section className="hero"><div className="eyebrow">ARCHITECTURAL CEILING INTELLIGENCE · CANADA</div><h1>Specify ceilings<br/><em>with confidence.</em></h1><p>ACUSTIQ is being built as a practical authority platform for architectural ceilings, suspended systems and acoustic design — connecting system education with real manufacturer products, technical documents and completed projects.</p><div className="actions"><A to="/systems" className="primary">Explore ceiling systems <ArrowRight size={18}/></A><A to="/for-matt" className="secondary">See what content we need</A></div><div className="note">Current concept imagery is clearly marked. Product claims, acoustic values and project photography will only be published from verified manufacturer source material.</div></section>
<ConceptVisual/>
<section className="section white"><div className="sectionhead"><div><span>01 / SYSTEMS</span><h2>Six system families ready for real product data.</h2></div><p>Each page already has an editorial structure. Matt can review the page and immediately see which product families, dimensions, finishes, test data, documents and photos belong there.</p></div><div className="cards">{systems.map((s,i)=><A to={`/systems/${s.slug}`} className="system-card" key={s.slug}><div className="num">0{i+1}</div><s.Icon size={30}/><h3>{s.title}</h3><p>{s.short}</p><span>Open system page <ArrowRight size={15}/></span></A>)}</div></section>
<section className="section dark"><div className="sectionhead"><div><span>02 / SPECIFY</span><h2>From inspiration to specification.</h2></div><p>ACUSTIQ is structured around the information architects and contractors actually need to make a decision — not generic marketing copy.</p></div><div className="four"><div><Database/><h3>Product data</h3><p>Dimensions, materials, finishes, acoustic performance, fire data and compatibility.</p></div><div><FileCode2/><h3>Design files</h3><p>CAD details, BIM/Revit objects, reflected ceiling layouts and typical sections.</p></div><div><Wrench/><h3>Installation</h3><p>Suspension, perimeter conditions, access, service integration and sequencing.</p></div><div><ImageIcon/><h3>Proof</h3><p>Real project photography, project credits, applications and install stories.</p></div></div></section>
<section className="section"><div className="sectionhead"><div><span>03 / TECHNICAL LIBRARY</span><h2>Authority content we can publish now.</h2></div><p>Generic technical education can move forward independently. Manufacturer-specific claims stay behind a verification line until the supporting source file arrives.</p></div><div className="resource-grid">{resources.map(([t,d,I]:any)=><A to="/technical-library" className="resource" key={t}><I/><div><h3>{t}</h3><p>{d}</p></div><ChevronRight/></A>)}</div></section>
<section className="matt-banner"><div><span>MATT / RAMBO CONTENT HANDOFF</span><h2>Give us the raw files. We’ll organize the rest.</h2><p>Photos can be unedited. PDFs can be messy. Product spreadsheets can be incomplete. The site now shows exactly where each piece will go.</p></div><A to="/for-matt" className="primary">Open content map <ArrowRight size={18}/></A></section>
</>}

function Systems(){return <section className="page"><div className="pagehero"><span>CEILING SYSTEMS</span><h1>Architectural ceiling system library.</h1><p>System-level education first; verified products and projects layered in as manufacturer material arrives.</p></div><div className="system-list">{systems.map((s,i)=><A key={s.slug} to={`/systems/${s.slug}`} className="system-row"><div className="index">0{i+1}</div><s.Icon/><div><h2>{s.title}</h2><p>{s.short}</p></div><ArrowRight/></A>)}</div></section>}

function NeedPanel({s}:{s:System}){return <aside className="need-panel"><div className="need-title"><ClipboardList/><div><span>MANUFACTURER CONTENT NEEDED</span><h3>What Matt should send for this page</h3></div></div><div className="need-grid"><div><h4>Product data</h4>{s.manufacturer.map(x=><p key={x}><CheckCircle2/>{x}</p>)}</div><div><h4>Files</h4>{s.docs.map(x=><p key={x}><Download/>{x}</p>)}</div><div><h4>Photography</h4><p><ImageIcon/>Hero image showing the system in a completed space</p><p><ImageIcon/>3–8 detail / installation / finish images</p><p><ImageIcon/>Project name, city, architect/designer and photographer credit</p></div></div></aside>}

function SystemDetail({s}:{s:System}){return <>
<section className="system-hero"><div><span>SYSTEM GUIDE</span><h1>{s.title}</h1><p>{s.intro}</p><div className="chips">{s.applications.map(x=><b key={x}>{x}</b>)}</div></div><ConceptVisual variant={s.slug.includes('metal')?'metal':s.slug.includes('baffle')?'baffle':'wood'}/></section>
<section className="content-two"><article><span>WHAT ACUSTIQ WILL EXPLAIN</span><h2>Design + specification questions</h2>{s.learn.map((x,i)=><div className="learn" key={x}><b>0{i+1}</b><div><h3>{x}</h3><p>This section will combine neutral technical guidance with manufacturer-verified examples, details and limitations.</p></div></div>)}</article><div className="spec-card"><span>PRODUCT RECORD TEMPLATE</span><h3>Every real product will be structured like this.</h3><dl><dt>Manufacturer</dt><dd>Pending verified source</dd><dt>Product family</dt><dd>Pending</dd><dt>Material</dt><dd>Pending</dd><dt>Dimensions</dt><dd>Pending</dd><dt>Acoustics</dt><dd>Verified test value only</dd><dt>Fire</dt><dd>Verified classification / report</dd><dt>Finishes</dt><dd>Manufacturer finish library</dd><dt>Documents</dt><dd>Data · Install · CAD · BIM · Warranty</dd></dl></div></section>
<NeedPanel s={s}/>
<section className="placeholder-section"><span>PROJECTS / HELD FOR REAL CONTENT</span><h2>Completed {s.title.toLowerCase()} projects will live here.</h2><p>We are intentionally not filling this with stock images or invented case studies. When Matt sends the real project package, this becomes a credible application gallery with project credits and product links.</p><div className="photo-slots">{[1,2,3].map(i=><div key={i}><ImageIcon/><b>REAL PROJECT PHOTO {i}</b><small>Awaiting manufacturer-approved photography</small></div>)}</div></section>
</>}

function Products(){return <section className="page"><div className="pagehero"><span>PRODUCT DATABASE</span><h1>Built for comparison, not brochure copy.</h1><p>These records will become the searchable product layer once Matt supplies the actual product families and supporting documents.</p></div><div className="product-schema"><div className="schema-main"><span>EXAMPLE RECORD STRUCTURE</span><h2>[Manufacturer] [Product Family]</h2><p className="muted">This is a content template — not a published product claim.</p><div className="facts">{['System type','Material','Module / dimensions','Edge / profile','NRC / acoustic value','CAC / isolation','Fire classification','Grid / carrier compatibility','Colours / finishes','Warranty'].map(x=><div key={x}><b>{x}</b><span>Manufacturer data pending</span></div>)}</div></div><div className="document-stack"><h3>Documents attached to the record</h3>{['Technical data sheet','Installation instructions','Specification section','CAD details','BIM / Revit family','Acoustic test report','Fire test report','EPD / HPD / sustainability','Warranty','Cleaning / maintenance'].map(x=><p key={x}><FileText/>{x}<em>pending</em></p>)}</div></div>
<div className="sectionhead compact"><div><span>COMPARISON FIELDS</span><h2>What makes the database useful.</h2></div><p>Once two or more comparable products are entered, ACUSTIQ can expose differences architects care about instead of making them open ten PDFs.</p></div><div className="comparison-row">{['Acoustics','Dimensions','Finish options','Fire','Suspension','Environmental docs'].map(x=><div key={x}><SwatchBook/><b>{x}</b><span>Compare across manufacturers</span></div>)}</div></section>}

function Technical(){return <section className="page"><div className="pagehero"><span>TECHNICAL LIBRARY</span><h1>Ceiling knowledge that earns authority.</h1><p>These are the cornerstone subjects we can build now using standards, primary sources and neutral technical explanations.</p></div><div className="article-grid">{resources.concat([
['9/16 vs 15/16 Ceiling Grid','Face width, appearance, compatibility and common applications.',Grid3X3],
['Tegular vs Square Lay-In','Edge geometry, shadow lines and grid compatibility.',PanelsTopLeft],
['Mineral Fibre vs Fiberglass','Materials, acoustics, durability and application tradeoffs.',BookOpen],
['Ceiling Clouds vs Baffles','How geometry changes appearance and acoustic strategy.',DraftingCompass],
['How to Estimate a T-Bar Ceiling','Room layout, waste, main tees, cross tees, wall angle and panels.',Ruler],
['Ceiling Coordination Checklist','What must be resolved with lighting, HVAC, sprinklers and access.',ClipboardList]
]).map(([t,d,I]:any,i)=><article key={t}><span>{String(i+1).padStart(2,'0')}</span><I/><h2>{t}</h2><p>{d}</p><button>Article framework ready</button></article>)}</div></section>}

function Matt(){const sections=[
['01','PRODUCT MASTER LIST','A spreadsheet, PDF catalogue, screenshots or even a rough email listing every ceiling product family. We will normalize names and taxonomy.'],
['02','TECHNICAL DATA','Dimensions, material, weights, acoustics, fire, suspension, tolerances, limitations and any test reports.'],
['03','FINISHES + SAMPLES','Colour charts, wood species, veneers, perforations, laminates, coatings, custom-colour rules and sample-order information.'],
['04','DESIGN FILES','CAD details, DWG/DXF, Revit/BIM, specification sections, reflected ceiling examples and typical perimeter details.'],
['05','INSTALLATION','Install manuals, suspension details, sequencing notes, seismic details, access methods and field photos.'],
['06','PROJECT PHOTOGRAPHY','Original high-resolution images plus project name, location, architect/designer, photographer and products used.'],
['07','COMPANY PROOF','Warranties, certifications, EPD/HPD, sustainability claims, testing, manufacturing locations and service territory.'],
['08','SALES KNOWLEDGE','The questions reps get every day, common mistakes, product substitutions, lead-time realities and what makes one system a better fit than another.']
]; return <section className="page matt-page"><div className="pagehero"><span>RAMBO / CONTENT MAP</span><h1>Matt: this is exactly what goes where.</h1><p>You do not need to write website copy. Send the raw source material. ACUSTIQ will turn it into structured product pages, technical references and real project case studies.</p></div><div className="intake">{sections.map(([n,t,d])=><div key={n}><b>{n}</b><div><h2>{t}</h2><p>{d}</p></div><CheckCircle2/></div>)}</div><div className="dropbox"><FileCheck2/><div><span>BEST HANDOFF FORMAT</span><h2>One messy folder is fine.</h2><p>Create folders called <b>Products</b>, <b>Technical PDFs</b>, <b>CAD-BIM</b>, <b>Finishes</b>, <b>Installation</b> and <b>Projects</b>. Drop everything you have in there. We will sort, rename, tag and map it into the site.</p></div></div><div className="held"><h2>What we are deliberately NOT inventing</h2><p>Real project names, product performance numbers, warranties, certifications, environmental claims, testing and manufacturer-specific installation requirements remain unpublished until the source file is in hand.</p></div></section>}

function App(){const [path,setPath]=React.useState(currentPath());React.useEffect(()=>{const f=()=>setPath(currentPath());window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f)},[]);let body:React.ReactNode=<Home/>;if(path==='/systems')body=<Systems/>;else if(path.startsWith('/systems/')){const s=systems.find(x=>`/systems/${x.slug}`===path);body=s?<SystemDetail s={s}/>:<Systems/>}else if(path==='/products')body=<Products/>;else if(path==='/technical-library')body=<Technical/>;else if(path==='/for-matt')body=<Matt/>;return <div className="site"><Header/><main>{body}</main><Footer/></div>}
export default App;
