import React from 'react';
import {createPortal} from 'react-dom';
import {ArrowRight, Building2, CheckCircle2, Grid3X3, Layers3, MousePointer2, PanelsTopLeft, PenTool, Sparkles, Upload, WandSparkles} from 'lucide-react';
import './enhancements.css';

const gallery = [
  {src:'/projects/linear-wood-feature-ceiling.webp',title:'Linear Wood Feature Ceiling',type:'Linear wood / architectural ceiling',description:'Real installation photography showing the visual rhythm, suspension zone and integrated services of a linear wood ceiling assembly.',tags:['Linear wood','Feature ceiling','Integrated services']},
  {src:'/projects/cloud-ceiling-finished.webp',title:'Finished Suspended Cloud Ceiling',type:'Acoustic cloud / custom ceiling',description:'Completed suspended ceiling feature with integrated lighting, showing how shaped ceiling elements can define a space while coordinating with building services.',tags:['Cloud ceiling','Integrated lighting','Finished installation']},
  {src:'/projects/real-unfinished-cloud-ceiling.jpg',title:'Cloud Ceiling Installation Detail',type:'Installation / specialty ceiling',description:'Real in-progress steel-stud and drywall cloud ceiling construction before final paint, showing the framing, boarding and field coordination behind the finished feature.',tags:['Installation','Steel stud','Drywall','Before paint']}
];

function Visualizer(){
  const [mode,setMode]=React.useState<'grid'|'cloud'|'wood'>('grid');
  return <section id="visualizer" className="visualizer-section" aria-labelledby="visualizer-title">
    <div className="visualizer-copy"><span>ROOM GRID + CEILING VISUALIZER</span><h2 id="visualizer-title">Sketch the room. Test the ceiling.</h2><p>Sketch or trace a room, set dimensions, choose a ceiling family, test layout and finish directions, then coordinate the ceiling plane with lights, diffusers, sprinklers and access points.</p><div className="visualizer-steps"><div><PenTool/><b>1. Sketch or trace</b><small>Start from a simple room outline, field dimensions or an imported plan.</small></div><div><Grid3X3/><b>2. Set the ceiling grid</b><small>Establish module direction, borders, clouds, baffles or linear runs.</small></div><div><WandSparkles/><b>3. Visualize systems</b><small>Switch ceiling styles and later manufacturer finishes and product assets.</small></div><div><MousePointer2/><b>4. Coordinate + specify</b><small>Place services, compare options and move toward product/specification records.</small></div></div><div className="visualizer-note"><Sparkles size={17}/><span>Use the concept preview now; the workflow can grow into deeper room-to-system visualization as verified product libraries are added.</span></div></div>
    <div className="visualizer-demo"><div className="demo-toolbar"><b>ROOM 01</b><span>24' × 18'</span><div>{(['grid','cloud','wood'] as const).map(x=><button key={x} onClick={()=>setMode(x)} className={mode===x?'active':''}>{x==='grid'?'T-Bar':x==='cloud'?'Clouds':'Linear Wood'}</button>)}</div></div><div className={`room-plan mode-${mode}`}><div className="room-label">CONCEPT ROOM</div><i className="service light one"/><i className="service light two"/><i className="service vent"/><i className="service sprinkler s1"/><i className="service sprinkler s2"/>{mode==='cloud'&&<><i className="cloud c1"/><i className="cloud c2"/><i className="cloud c3"/></>}{mode==='wood'&&<div className="wood-lines">{Array.from({length:15}).map((_,i)=><i key={i}/>)}</div>}</div><div className="demo-footer"><span><i className="legend light"/> Lighting</span><span><i className="legend vent"/> HVAC</span><span><i className="legend sprinkler"/> Sprinklers</span><b>Click system tabs to preview</b></div></div>
  </section>
}
function Gallery(){return <section id="gallery" className="real-gallery" aria-labelledby="real-gallery-title"><div className="gallery-head"><div><span>REAL INSTALLATIONS / SYSTEM INSPIRATION</span><h2 id="real-gallery-title">Ceiling systems in the field.</h2></div><p>Real installation photography gives designers and contractors a better starting point than generic product renders alone. Project imagery helps explain system types, details, coordination and finish possibilities.</p></div><div className="gallery-grid">{gallery.map((item,i)=><article className={i===0?'gallery-card gallery-card-wide':'gallery-card'} key={item.src}><div className="gallery-image"><img src={item.src} alt={item.title} loading={i===0?'eager':'lazy'}/><span>{item.type}</span></div><div className="gallery-copy"><h3>{item.title}</h3><p>{item.description}</p><div className="gallery-tags">{item.tags.map(tag=><b key={tag}>{tag}</b>)}</div></div></article>)}</div><div className="gallery-paths"><div><PanelsTopLeft/><h3>Explore systems</h3><p>Compare ceiling families, applications and design considerations.</p><a href="/systems">Browse ceiling systems <ArrowRight size={16}/></a></div><div><Layers3/><h3>Build technical knowledge</h3><p>Learn grid, acoustics, coordination, seismic concepts and specification language.</p><a href="/technical-library">Open technical library <ArrowRight size={16}/></a></div><div><Building2/><h3>Product knowledge</h3><p>Verified product data and manufacturer files can layer onto the system knowledge.</p><a href="/product-knowledge">Explore product knowledge <ArrowRight size={16}/></a></div></div></section>}
function IndustryPage(){return <section className="industry-page"><div className="industry-hero"><span>INDUSTRY CONTRIBUTIONS</span><h1>Put good ceiling information to work.</h1><p>Manufacturers, representatives, installers and technical specialists can contribute verified source material that improves product discovery, specification support and visualization.</p></div></section>}
function GuestPostPage(){return <section className="guest-page"><div className="guest-hero"><span>CONTRIBUTE / GUEST POST</span><div className="guest-price">$10</div><h1>Guest post with ACUSTIQ.</h1><p>Share useful ceiling, acoustic, architectural or construction knowledge with a focused industry audience.</p></div></section>}
function FooterB2B(){return <nav className="footer-b2b" aria-label="Industry and contributor links"><span>B2B / INDUSTRY</span><a href="/for-matt">Industry contributions</a><a href="/for-matt">Contribute manufacturer assets</a><a href="/guest-post">Guest post with us — $10</a><a href="/product-knowledge">Product & launch updates</a></nav>}
export default function Enhancements(){const [target,setTarget]=React.useState<HTMLElement|null>(null);const [footerTarget,setFooterTarget]=React.useState<HTMLElement|null>(null);const [path,setPath]=React.useState(window.location.pathname);React.useEffect(()=>{const mount=()=>{const nextPath=window.location.pathname;setPath(nextPath);const main=document.querySelector('.site main') as HTMLElement|null;const early=document.querySelector('#home-visual-tools-anchor') as HTMLElement|null;setTarget(nextPath==='/'&&early?early:main);setFooterTarget(document.querySelector('.site footer') as HTMLElement|null);};mount();const onNav=()=>setTimeout(mount,0);window.addEventListener('popstate',onNav);return()=>window.removeEventListener('popstate',onNav)},[]);const portals:React.ReactNode[]=[];if(target){if(path==='/for-matt')portals.push(createPortal(<div data-enhancement-portal="true"><IndustryPage/></div>,target));else if(path==='/guest-post')portals.push(createPortal(<div data-enhancement-portal="true"><GuestPostPage/></div>,target));else if(path==='/')portals.push(createPortal(<div data-enhancement-portal="true"><Visualizer/><Gallery/></div>,target));}if(footerTarget)portals.push(createPortal(<FooterB2B/>,footerTarget));return <>{portals}</>}
