import React from 'react';
import {createPortal} from 'react-dom';
import {ArrowRight, Building2, Grid3X3, Layers3, MousePointer2, PanelsTopLeft, PenTool, Sparkles, WandSparkles} from 'lucide-react';
import './enhancements.css';
const gallery=[
 {src:'/projects/rwc-featured/ilm-disney-acoustic-baffles.jpg',title:'Coloured Acoustic Baffles',type:'Rambo Walls & Ceilings · ILM / Disney',description:'Real suspended acoustic baffles show how colour, depth, spacing, lighting and open-plenum services work together.',tags:['Acoustic baffles','Open plenum','Real project'],href:'/systems/acoustic-baffles'},
 {src:'/projects/rwc-featured/microsoft-acoustic-clouds-wide.jpg',title:'Illuminated Acoustic Clouds',type:'Rambo Walls & Ceilings · Microsoft',description:'Large suspended acoustic clouds use integrated perimeter lighting to create a distinct ceiling plane below exposed services.',tags:['Acoustic clouds','Integrated lighting','Real project'],href:'/systems/acoustic-clouds'},
 {src:'/projects/rwc-featured/southpoint-wood-slat-acoustic-ceiling.jpg',title:'Linear Wood Slat Ceiling',type:'Rambo Walls & Ceilings',description:'A real wood slat ceiling installation showing carrier rhythm, lighting coordination and the transition to adjacent ceiling systems.',tags:['Linear wood','Acoustic ceiling','Real project'],href:'/systems/linear-wood'},
 {src:'/projects/rwc-archive/20211005_130715.jpg',title:'Commercial T-Bar Ceiling',type:'Rambo Walls & Ceilings',description:'Finished commercial suspended ceiling grid coordinated with acoustic panels, lights and diffusers.',tags:['T-bar','Commercial ceiling','Real project'],href:'/systems/suspended-tbar'},
 {src:'/projects/rwc-archive/20220803_121928.jpg',title:'Linear Blade Ceiling',type:'Rambo Walls & Ceilings',description:'A dense linear blade ceiling field showing open joints, repetition and access to the support zone above.',tags:['Linear ceiling','Ceiling blades','Real project'],href:'/systems/linear-metal'},
 {src:'/projects/steelstud-archive/commercial-ceiling.jpg',title:'Curved Coloured Canopy',type:'SteelStud.ca legacy archive',description:'Recovered legacy project photography of a suspended curved blue ceiling feature.',tags:['Specialty ceiling','Curved canopy','Legacy project'],href:'/systems/specialty'},
 {src:'/projects/steelstud-archive/formation-ceiling.jpg',title:'Circular Ceiling Islands',type:'SteelStud.ca legacy archive',description:'Recovered legacy photography showing overlapping circular islands below an exposed ceiling.',tags:['Ceiling islands','Specialty ceiling','Legacy project'],href:'/systems/acoustic-clouds'},
 {src:'/projects/837-beatty-tectum-wall-finished.jpg',title:'837 Beatty Acoustic Wall Panels',type:'Rambo Walls & Ceilings · documented project',description:'Seven real installation photographs follow the beveled acoustic wall panels from material and layout through the completed field.',tags:['Tectum panels','Vancouver','Real project'],href:'/systems/acoustic-panels'}
];
function Visualizer(){const[mode,setMode]=React.useState<'grid'|'cloud'|'wood'>('grid');return <section id="visualizer" className="visualizer-section"><div className="visualizer-copy"><span>ROOM GRID + CEILING VISUALIZER</span><h2>Sketch the room. Test the ceiling.</h2><p>Sketch or trace a room, set dimensions, choose a ceiling family, test layout and finish directions, then coordinate the ceiling plane with lights, diffusers, sprinklers and access points.</p><div className="visualizer-steps"><div><PenTool/><b>1. Sketch or trace</b><small>Start from a room outline, field dimensions or imported plan.</small></div><div><Grid3X3/><b>2. Set the ceiling grid</b><small>Establish module direction, borders, clouds, baffles or linear runs.</small></div><div><WandSparkles/><b>3. Visualize systems</b><small>Switch ceiling styles and later manufacturer finishes and product assets.</small></div><div><MousePointer2/><b>4. Coordinate + specify</b><small>Place services and compare options.</small></div></div><div className="visualizer-note"><Sparkles size={17}/><span>Test the concept now; deeper product visualization can layer in as verified manufacturer libraries are added.</span></div></div><div className="visualizer-demo"><div className="demo-toolbar"><b>ROOM 01</b><span>24' × 18'</span><div>{(['grid','cloud','wood'] as const).map(x=><button key={x} onClick={()=>setMode(x)} className={mode===x?'active':''}>{x==='grid'?'T-Bar':x==='cloud'?'Clouds':'Linear Wood'}</button>)}</div></div><div className={`room-plan mode-${mode}`}><div className="room-label">CONCEPT ROOM</div><i className="service light one"/><i className="service light two"/><i className="service vent"/><i className="service sprinkler s1"/><i className="service sprinkler s2"/>{mode==='cloud'&&<><i className="cloud c1"/><i className="cloud c2"/><i className="cloud c3"/></>}{mode==='wood'&&<div className="wood-lines">{Array.from({length:15}).map((_,i)=><i key={i}/>)}</div>}</div><div className="demo-footer"><span>Lighting</span><span>HVAC</span><span>Sprinklers</span><b>Click system tabs to preview</b></div></div></section>}
function Gallery(){return <section id="gallery" className="real-gallery"><div className="gallery-head"><div><span>REAL INSTALLATIONS / SYSTEM INSPIRATION</span><h2>Ceiling systems in the field.</h2></div><p>Eight real examples from Rambo Walls & Ceilings and the recovered SteelStud.ca archive connect directly to the full system guides. The complete Rambo contractor gallery contains 59 photographs.</p></div><div className="gallery-grid">{gallery.map((item:any,i)=><article className={i===0?'gallery-card gallery-card-wide':'gallery-card'} key={item.title}><div className="gallery-image"><img src={item.src} alt={item.title} loading={i===0?'eager':'lazy'}/><span>{item.type}</span></div><div className="gallery-copy"><h3>{item.title}</h3><p>{item.description}</p>{item.href&&<a href={item.href}>Open this ceiling guide <ArrowRight size={16}/></a>}<div className="gallery-tags">{item.tags.map((tag:string)=><b key={tag}>{tag}</b>)}</div></div></article>)}</div><div className="gallery-paths"><div><PanelsTopLeft/><h3>Explore systems</h3><a href="/systems">Browse all eight ceiling systems <ArrowRight size={16}/></a></div><div><Layers3/><h3>Full Rambo gallery</h3><a href="/contractors/rambo-walls-ceilings">View 59 project photos <ArrowRight size={16}/></a></div><div><Building2/><h3>Product knowledge</h3><a href="/product-knowledge">Explore products <ArrowRight size={16}/></a></div></div></section>}
function FooterB2B(){return <nav className="footer-b2b"><span>B2B / INDUSTRY</span><a href="/for-matt">Industry contributions</a><a href="/guest-post">Guest post with us — $10</a><a href="/product-knowledge">Product & launch updates</a></nav>}
export default function Enhancements(){const[target,setTarget]=React.useState<HTMLElement|null>(null);const[footer,setFooter]=React.useState<HTMLElement|null>(null);const[path,setPath]=React.useState(location.pathname);React.useEffect(()=>{const mount=()=>{setPath(location.pathname);const main=document.querySelector('.site main') as HTMLElement|null;const early=document.querySelector('#home-visual-tools-anchor') as HTMLElement|null;setTarget(location.pathname==='/'&&early?early:main);setFooter(document.querySelector('.site footer') as HTMLElement|null)};mount();addEventListener('popstate',mount);return()=>removeEventListener('popstate',mount)},[]);return <>{target&&path==='/'&&createPortal(<div data-enhancement-portal="true"><Visualizer/><Gallery/></div>,target)}{footer&&createPortal(<FooterB2B/>,footer)}</>}
