import React from 'react';
import {ArrowRight, BookOpen, CheckCircle2, ExternalLink, Layers3, PackageSearch, Sparkles} from 'lucide-react';
import './product-knowledge.css';

type Product={maker:string;name:string;system:string;material:string;performance:string;why:string;url:string;tags:string[]};
const products:Product[]=[
{maker:'Armstrong Ceiling Solutions',name:'FELTWORKS Blades – VARAFFIX',system:'Acoustic Baffles',material:'Recycled PET felt',performance:'Class A fire performance; up to 60% recycled content on listed configurations',why:'Reinforced rectangular felt blades create a clean linear acoustic field with multiple sizes and finish options. A strong reference when the design intent is soft texture, colour and open-plenum acoustics.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/ceilings/feltworks-ceiling-family.html',tags:['Felt','Linear','Open plenum','Colour options']},
{maker:'Armstrong Ceiling Solutions',name:'FELTWORKS Blades – HookOn',system:'Acoustic Baffles',material:'Recycled PET felt',performance:'HookOn families list acoustic options up to NRC 0.85 on selected kits',why:'HookOn rectangular, Ebbs & Flows and Peaks & Valleys kits show how baffles can move beyond straight repeated blades into shaped ceiling topography.',url:'https://www.armstrongceilings.com/commercial/en/articles/felt-acoustic-blades.html',tags:['Acoustic','Shaped kits','PET','Suspended']},
{maker:'Armstrong Ceiling Solutions',name:'SOUNDSCAPES Blades',system:'Acoustic Baffles',material:'Fiberglass',performance:'Class A fire performance; multiple sizes and options',why:'A fiberglass blade family for exposed-structure spaces where acoustic absorption and a crisp vertical architectural element are both important.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/acoustic-baffles-blades.html',tags:['Fiberglass','Baffles','Commercial','Acoustic']},
{maker:'Armstrong Ceiling Solutions',name:'METALWORKS Blades – Classics',system:'Linear Metal / Baffles',material:'Metal',performance:'Class A fire performance on listed product data',why:'Useful when the project wants the rhythm of a blade ceiling with a harder, more precise metal expression instead of felt or fibre.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/acoustic-baffles-blades.html',tags:['Metal','Linear','Durable','Blade ceiling']},
{maker:'Armstrong Ceiling Solutions',name:'FELTWORKS Open Cell',system:'Open Cell',material:'Recycled PET felt',performance:'Selected kits list NRC 0.80 and Class A fire performance',why:'Open-cell felt modules combine visual screening and absorption. Kits can be used as individual clouds or linked into larger ceiling fields depending on the product configuration.',url:'https://www.armstrongceilings.com/commercial/en/articles/felt-open-cell-acoustic-panels.html',tags:['Open cell','Felt','Acoustic','Clouds']},
{maker:'CGC / USG Ceilings Plus',name:'Beamz™',system:'Open Plenum Baffles + Pods',material:'Architectural ceiling assembly',performance:'Acoustic options available with perforations and sound-absorbing materials',why:'Interconnected baffles and factory-assembled pods demonstrate how open-plenum ceilings can become modular architectural structures while coordinating independently suspended lights, diffusers, speakers and sprinklers.',url:'https://www.usg.com/en-CA/p/product/ceilings-plus-design-solutions-beamz-interconnected-baffles-and-pods-SC2299',tags:['Pods','Baffles','Open plenum','Service integration']},
{maker:'Armstrong Ceiling Solutions',name:'Divy Baffle',system:'Acoustic Baffles',material:'PET felt',performance:'NRC 0.75 and Class A fire performance on current listed data',why:'A contemporary PET baffle option that illustrates the lighter, modular end of acoustic blade design for commercial interiors.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/acoustic-baffles-blades.html',tags:['PET','NRC 0.75','Class A','Baffle']},
{maker:'Armstrong Ceiling Solutions',name:'FELTWORKS Acoustical Ceiling Panels',system:'Acoustic Panels',material:'PET felt',performance:'Current listed configurations show NRC 0.75–0.80 depending on mounting',why:'A useful comparison to suspended baffles: flat felt panels can provide a quieter visual plane where the design does not need vertical blades.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/ceilings/feltworks-ceiling-family.html',tags:['Panels','PET','Acoustic','Retrofit']}
];
const groups=['All','Acoustic Baffles','Open Cell','Linear Metal / Baffles','Acoustic Panels'];
export default function ProductKnowledgePage(){const [filter,setFilter]=React.useState('All');const shown=filter==='All'?products:products.filter(p=>p.system===filter);const schema={'@context':'https://schema.org','@type':'CollectionPage','name':'Architectural Ceiling Product Knowledge','description':'ACUSTIQ guide to real architectural ceiling products, systems, materials and applications.','url':'https://www.acustiq.ca/product-knowledge','mainEntity':products.map(p=>({'@type':'Product','name':p.name,'brand':{'@type':'Brand','name':p.maker},'category':p.system,'material':p.material,'url':p.url}))};return <div className="pk-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><header className="pk-top"><a href="/" className="pk-brand">ACUSTIQ<span>.</span></a><nav><a href="/systems">Systems</a><a href="/visualizer">Visualizer</a><a href="/product-knowledge">Product Knowledge</a><a href="/technical-library">Technical Library</a></nav><a href="/installers/vancouver" className="pk-cta">Get installation pricing</a></header><main>
<section className="pk-hero"><div><span>REAL PRODUCTS / PRODUCT KNOWLEDGE</span><h1>See what architectural ceilings can actually be.</h1><p>Explore real ceiling products and product families from established manufacturers. ACUSTIQ explains what the systems are, where they fit, what to compare and how they can move from inspiration into a coordinated project.</p><div className="pk-hero-actions"><a href="#products">Explore products <ArrowRight/></a><a href="/visualizer">Try a ceiling concept <Sparkles/></a></div></div><aside><PackageSearch/><b>PRODUCT DISCOVERY, NOT A STORE</b><p>These are educational product references and sourcing leads. Availability, exact performance, finishes, dimensions and suitability must be confirmed from the current manufacturer documentation for the selected product.</p></aside></section>
<section className="pk-explain"><div><span>HOW TO USE THIS LIBRARY</span><h2>Start with the look. Learn the system. Then narrow the product.</h2></div><div className="pk-steps"><article><b>01</b><h3>Choose the ceiling idea</h3><p>Baffles, open cell, linear metal, felt panels, clouds, wood and other architectural ceiling families.</p></article><article><b>02</b><h3>Compare real products</h3><p>Look at material, geometry, acoustic approach, finish range, access and installation method — not just the room photograph.</p></article><article><b>03</b><h3>Verify the selected system</h3><p>Use current manufacturer data sheets, specifications, installation instructions, CAD/BIM and tested performance before final specification or ordering.</p></article></div></section>
<section id="products" className="pk-products"><div className="pk-heading"><div><span>FEATURED PRODUCT KNOWLEDGE</span><h2>Real systems worth knowing.</h2></div><p>This library will keep expanding as new products, applications, finishes and verified manufacturer assets become available.</p></div><div className="pk-filters">{groups.map(g=><button className={filter===g?'active':''} onClick={()=>setFilter(g)} key={g}>{g}</button>)}</div><div className="pk-grid">{shown.map((p,i)=><article key={p.name}><div className="pk-num">{String(i+1).padStart(2,'0')}</div><span>{p.system}</span><h3>{p.name}</h3><h4>{p.maker}</h4><div className="pk-spec"><p><b>Material</b>{p.material}</p><p><b>Performance snapshot</b>{p.performance}</p></div><p className="pk-why">{p.why}</p><div className="pk-tags">{p.tags.map(t=><b key={t}>{t}</b>)}</div><a href={p.url} target="_blank" rel="noreferrer">Manufacturer product information <ExternalLink/></a></article>)}</div></section>
<section className="pk-knowledge"><div><BookOpen/><span>PRODUCT KNOWLEDGE</span><h2>What should you compare before choosing a ceiling product?</h2></div><div><details open><summary>Material and visual character</summary><p>Felt, fiberglass, mineral fibre, metal and wood-based systems can produce similar overall ceiling forms but behave differently in weight, edge detail, texture, durability, finish range and installation. Start with the design intent, then understand what material best supports it.</p></details><details><summary>Acoustic performance</summary><p>Do not compare products by the word “acoustic” alone. Look at the tested metric and mounting condition. Free-hanging baffles and clouds may be described by Sabins or by system-specific NRC data, while continuous ceiling panels may use NRC/CAC and other ratings. Compare like with like.</p></details><details><summary>Fire and code information</summary><p>Use the current manufacturer documentation for the exact product and configuration. A fire classification shown for one family or finish should not automatically be applied to another.</p></details><details><summary>Suspension, access and services</summary><p>The best-looking product can still be the wrong choice if it prevents required access or conflicts with lights, sprinklers, diffusers and structure. Carrier spacing, cable locations, module geometry and independent service support should be coordinated early.</p></details><details><summary>Finish and colour</summary><p>Finish libraries are part of the design tool. Felt can provide saturated colour and soft texture; metal can provide precise coated surfaces; wood brings grain and natural variation. Samples and manufacturer-approved visualization assets are valuable before final selection.</p></details></div></section>
<section className="pk-source"><Layers3/><div><span>NEED A PRODUCT FOR YOUR PROJECT?</span><h2>ACUSTIQ can help narrow the ceiling system and sourcing path.</h2><p>Use the system guides and visualizer to define the look and room requirements. For Lower Mainland projects, the concept can then move toward installation pricing through ACUSTIQ's featured regional installer.</p></div><a href="/installers/vancouver">Start with installation pricing <ArrowRight/></a></section>
<section className="pk-manufacturer"><div><span>FOR CEILING MANUFACTURERS</span><h2>Want your products represented better?</h2><p>ACUSTIQ is building product knowledge around useful customer decisions. Approved room photography, finish libraries, technical data, CAD/BIM, installation documents and launch information let us build richer product records and visualizer choices.</p></div><a href="/for-matt">Contribute manufacturer assets <ArrowRight/></a></section>
</main></div>}
