import React from 'react';
import {ArrowRight, BookOpen, ExternalLink, Layers3, PackageSearch, Sparkles} from 'lucide-react';
import './product-knowledge.css';

type Product={maker:string;name:string;system:string;material:string;performance:string;why:string;url:string;tags:string[]};
const products:Product[]=[
{maker:'Armstrong Ceiling Solutions',name:'FELTWORKS Blades – VARAFFIX',system:'Acoustic Baffles',material:'Recycled PET felt',performance:'Class A fire performance; 60% recycled content listed',why:'Reinforced rectangular felt blades create a clean linear acoustic field with multiple sizes and finish options. A strong reference when the design intent is soft texture, colour and open-plenum acoustics.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/acoustic-baffles-blades.html',tags:['Felt','Linear','Open plenum','Colour options']},
{maker:'Armstrong Ceiling Solutions',name:'FELTWORKS Blades – HookOn Ebbs & Flows',system:'Acoustic Baffles',material:'Recycled PET felt',performance:'NRC 0.85; Class A; up to 50% recycled content on current listing',why:'A useful example of baffles becoming ceiling topography rather than simple repeated blades. The kit creates a flowing profile while retaining the soft visual and acoustic function of felt.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/feltworks-blades-hookon-ebbs-and-flows-ceiling-kits.html',tags:['NRC 0.85','Shaped kit','PET','Suspended']},
{maker:'Armstrong Ceiling Solutions',name:'FELTWORKS Blades – HookOn Peaks & Valleys',system:'Acoustic Baffles',material:'Recycled PET felt',performance:'NRC 0.85; Class A; up to 50% recycled content on current listing',why:'Alternating blade profiles create a more sculptural ceiling field while maintaining accessible, modular suspended elements.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/acoustic-baffles-blades.html',tags:['Acoustic','Topography','PET','Modular']},
{maker:'Armstrong Ceiling Solutions',name:'SOUNDSCAPES Blades',system:'Acoustic Baffles',material:'Fiberglass',performance:'Class A fire performance; 43–53% recycled content listed',why:'A fiberglass blade family for exposed-structure spaces where sound absorption and a crisp vertical architectural element are both important.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/acoustic-baffles-blades.html',tags:['Fiberglass','Baffles','Commercial','Acoustic']},
{maker:'Armstrong Ceiling Solutions',name:'Divy Baffle',system:'Acoustic Baffles',material:'PET felt',performance:'NRC 0.75; Class A on current listed data',why:'A contemporary PET baffle option illustrating the lighter, modular end of acoustic blade design for commercial interiors.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/acoustic-baffles-blades.html',tags:['PET','NRC 0.75','Class A','Baffle']},
{maker:'Armstrong Ceiling Solutions',name:'Hush Slim Baffle',system:'Acoustic Baffles',material:'PET felt',performance:'NRC 0.70; Class B on current listed data',why:'A slim felt baffle useful for understanding that not every visually similar baffle has the same acoustic or fire classification. Exact product data matters.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/felt-ceiling-panels.html',tags:['Slim profile','PET','NRC 0.70','Baffle']},
{maker:'Armstrong Ceiling Solutions',name:'TECTUM Blades and Baffles',system:'Acoustic Baffles',material:'TECTUM wood fibre',performance:'Current listing shows Sabin values up to 0.50 depending on configuration',why:'Wood-fibre blades provide a visibly different texture from PET or fiberglass and are useful where a more robust, tactile architectural surface is desired.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/acoustic-baffles-blades.html',tags:['Wood fibre','Textured','Durable','Baffle']},
{maker:'Rockfon',name:'Contour Baffles',system:'Acoustic Baffles',material:'Stone wool',performance:'Rockfon lists configurations up to 8.0 sabins',why:'Frameless stone-wool baffles can be arranged as linear fields, waves and shaped compositions, giving designers another material route to open-plenum acoustic control.',url:'https://www.rockfon.com/en-us/products/categories/islands-baffles/',tags:['Stone wool','Up to 8 sabins','Frameless','Shapes']},
{maker:'Rockfon',name:'Sequence Linear Metal Beam Baffles',system:'Linear Metal / Baffles',material:'Metal',performance:'Open-plenum linear metal baffle system; verify configuration-specific performance',why:'Long continuous metal beams in different widths and heights can create a defined ceiling plane while retaining the openness of the plenum.',url:'https://www.rockfon.com/en-us/products/categories/islands-baffles/',tags:['Metal','Linear beams','Open plenum','Depth variation']},
{maker:'Rockfon',name:'Intaline Round Base Baffles',system:'Linear Metal / Baffles',material:'Metal',performance:'Architectural metal baffle; verify current product documentation for selected configuration',why:'A metal baffle option designed to provide a focal point or visually mask the plenum, useful when the design intent is more precise and durable than soft felt.',url:'https://www.rockfon.com/en-us/products/categories/islands-baffles/',tags:['Metal','Round base','Visual screening','Baffle']},
{maker:'Armstrong Ceiling Solutions',name:'METALWORKS Blades – Classics',system:'Linear Metal / Baffles',material:'Metal',performance:'Class A fire performance on current listed product data',why:'A blade ceiling with a harder, more precise metal expression instead of felt or fibre. Useful for durable commercial interiors and linear visual rhythm.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/acoustic-baffles-blades.html',tags:['Metal','Linear','Durable','Blade ceiling']},
{maker:'Armstrong Ceiling Solutions',name:'FELTWORKS Open Cell – Rectangles',system:'Open Cell',material:'Recycled PET felt',performance:'NRC 0.80; Class A; up to 50% recycled content on current listing',why:'Open-cell felt modules combine visual screening and absorption. Rectangular kits can be used to create a softer alternative to traditional metal open-cell ceilings.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/ceilings/feltworks-ceiling-family.html',tags:['Open cell','Felt','NRC 0.80','Modular']},
{maker:'Armstrong Ceiling Solutions',name:'FELTWORKS Open Cell – Ebbs & Flows',system:'Open Cell',material:'Recycled PET felt',performance:'NRC 0.80; Class A; up to 50% recycled content on current listing',why:'Shaped open-cell modules demonstrate how visual screening, acoustic absorption and ceiling topography can be combined in one modular system.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/ceilings/feltworks-ceiling-family.html',tags:['Open cell','Shaped','Acoustic','PET']},
{maker:'CGC / USG Ceilings Plus',name:'Beamz™',system:'Open Cell',material:'Interconnected architectural baffles and pods',performance:'Acoustic options use perforations and sound-absorbing materials',why:'Factory-assembled pods and loose beam options can form open-cell ceiling structures. CGC specifically notes third-party integration of diffusers, lights, speakers, sprinklers and Wi-Fi when independently suspended.',url:'https://www.usg.com/en-CA/p/product/ceilings-plus-design-solutions-beamz-interconnected-baffles-and-pods-SC2299',tags:['Pods','Open cell','Services','Acoustic options']},
{maker:'Rockfon',name:'Rockfon Islands',system:'Acoustic Clouds',material:'Stone wool',performance:'Class A to ASTM E84 and CAN/ULC S102; high acoustic performance',why:'Frameless stone-wool clouds are a strong reference for open-plenum acoustic correction. Rockfon positions them for creative layouts where a full wall-to-wall ceiling is not required.',url:'https://www.rockfon.com/en-us/products/rockfon-islands/',tags:['Stone wool','Cloud','Class A','Open plenum']},
{maker:'Armstrong Ceiling Solutions',name:'FELTWORKS Acoustical Ceiling Panels',system:'Acoustic Panels',material:'PET felt',performance:'NRC 0.75 A mounting / 0.80 D-20 mounting on current listing',why:'Flat felt panels provide a quieter visual plane where the design does not need vertical blades. They also demonstrate why mounting condition belongs beside an NRC number.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/ceilings/feltworks-ceiling-family.html',tags:['Panels','PET','NRC 0.75–0.80','Retrofit']},
{maker:'Armstrong Ceiling Solutions',name:'Tetria Ceiling Panels',system:'Acoustic Panels',material:'PET felt',performance:'Current listing shows sound absorption up to NRC 0.90',why:'A higher-absorption felt panel option that expands the product library beyond blades and shows how panel geometry and mounting can change acoustic performance.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/felt-ceiling-panels.html',tags:['PET','Panels','Up to NRC 0.90','Acoustic']},
{maker:'Armstrong Ceiling Solutions',name:'Clario Ceiling Panels',system:'Acoustic Panels',material:'PET felt',performance:'NRC 0.70 on current listing',why:'A simpler felt ceiling-panel reference useful for comparing flat absorptive products against baffles, open-cell kits and sculptural ceiling systems.',url:'https://www.armstrongceilings.com/commercial/en/commercial-ceilings-walls/felt-ceiling-panels.html',tags:['PET','Panels','NRC 0.70','Felt']}
];
const groups=['All','Acoustic Baffles','Open Cell','Acoustic Clouds','Linear Metal / Baffles','Acoustic Panels'];
export default function ProductKnowledgePage(){const [filter,setFilter]=React.useState('All');const shown=filter==='All'?products:products.filter(p=>p.system===filter);const schema={'@context':'https://schema.org','@type':'CollectionPage','name':'Architectural Ceiling Product Knowledge','description':'ACUSTIQ guide to real architectural ceiling products, systems, materials and applications.','url':'https://www.acustiq.ca/product-knowledge','mainEntity':products.map(p=>({'@type':'Product','name':p.name,'brand':{'@type':'Brand','name':p.maker},'category':p.system,'material':p.material,'url':p.url}))};return <div className="pk-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><header className="pk-top"><a href="/" className="pk-brand">ACUSTIQ<span>.</span></a><nav><a href="/systems">Systems</a><a href="/visualizer">Visualizer</a><a href="/product-knowledge">Product Knowledge</a><a href="/technical-library">Technical Library</a></nav><a href="/installers/vancouver" className="pk-cta">Get installation pricing</a></header><main>
<section className="pk-hero"><div><span>REAL PRODUCTS / PRODUCT KNOWLEDGE</span><h1>See what architectural ceilings can actually be.</h1><p>Explore real ceiling products and product families from established manufacturers. ACUSTIQ explains what the systems are, where they fit, what to compare and how they can move from inspiration into a coordinated project.</p><div className="pk-hero-actions"><a href="#products">Explore products <ArrowRight/></a><a href="/visualizer">Try a ceiling concept <Sparkles/></a></div></div><aside><PackageSearch/><b>PRODUCT DISCOVERY, NOT A STORE</b><p>These are educational product references and sourcing leads. Availability, exact performance, finishes, dimensions and suitability must be confirmed from the current manufacturer documentation for the selected product.</p></aside></section>
<section className="pk-explain"><div><span>HOW TO USE THIS LIBRARY</span><h2>Start with the look. Learn the system. Then narrow the product.</h2></div><div className="pk-steps"><article><b>01</b><h3>Choose the ceiling idea</h3><p>Baffles, open cell, linear metal, felt panels, clouds, wood and other architectural ceiling families.</p></article><article><b>02</b><h3>Compare real products</h3><p>Look at material, geometry, acoustic approach, finish range, access and installation method — not just the room photograph.</p></article><article><b>03</b><h3>Verify the selected system</h3><p>Use current manufacturer data sheets, specifications, installation instructions, CAD/BIM and tested performance before final specification or ordering.</p></article></div></section>
<section id="products" className="pk-products"><div className="pk-heading"><div><span>FEATURED PRODUCT KNOWLEDGE</span><h2>Real systems worth knowing.</h2></div><p>This library keeps expanding as new products, applications, finishes and verified manufacturer information become available.</p></div><div className="pk-filters">{groups.map(g=><button className={filter===g?'active':''} onClick={()=>setFilter(g)} key={g}>{g}</button>)}</div><div className="pk-grid">{shown.map((p,i)=><article key={`${p.maker}-${p.name}`}><div className="pk-num">{String(i+1).padStart(2,'0')}</div><span>{p.system}</span><h3>{p.name}</h3><h4>{p.maker}</h4><div className="pk-spec"><p><b>Material</b>{p.material}</p><p><b>Performance snapshot</b>{p.performance}</p></div><p className="pk-why">{p.why}</p><div className="pk-tags">{p.tags.map(t=><b key={t}>{t}</b>)}</div><a href={p.url} target="_blank" rel="noreferrer">Manufacturer product information <ExternalLink/></a></article>)}</div></section>
<section className="pk-knowledge"><div><BookOpen/><span>PRODUCT KNOWLEDGE</span><h2>What should you compare before choosing a ceiling product?</h2></div><div><details open><summary>Material and visual character</summary><p>Felt, fiberglass, stone wool, wood fibre and metal systems can produce related ceiling forms but behave differently in weight, edge detail, texture, durability, finish range and installation. Start with the design intent, then understand which material supports it.</p></details><details><summary>Acoustic performance</summary><p>Do not compare products by the word “acoustic” alone. Look at the tested metric and mounting condition. Baffles and clouds may use Sabins or configuration-specific NRC values, while continuous panels may use NRC and other ratings. Compare like with like.</p></details><details><summary>Fire and code information</summary><p>Use current manufacturer documentation for the exact product and configuration. A fire classification shown for one family or finish should not automatically be applied to another.</p></details><details><summary>Suspension, access and services</summary><p>The best-looking product can still be wrong if it prevents required access or conflicts with lights, sprinklers, diffusers and structure. Carrier spacing, cable locations, module geometry and independent service support should be coordinated early.</p></details><details><summary>Finish and colour</summary><p>Finish libraries are part of the design tool. Felt can provide saturated colour and soft texture; metal can provide precise coated surfaces; wood and wood fibre bring grain or tactile texture. Samples and manufacturer-approved visualization assets are valuable before final selection.</p></details></div></section>
<section className="pk-source"><Layers3/><div><span>NEED A PRODUCT FOR YOUR PROJECT?</span><h2>ACUSTIQ can help narrow the ceiling system and sourcing path.</h2><p>Use the system guides and visualizer to define the look and room requirements. For Lower Mainland projects, the concept can then move toward installation pricing through ACUSTIQ's featured regional installer.</p></div><a href="/installers/vancouver">Start with installation pricing <ArrowRight/></a></section>
<section className="pk-manufacturer"><div><span>FOR CEILING MANUFACTURERS</span><h2>Want your products represented better?</h2><p>Approved room photography, finish libraries, technical data, CAD/BIM, installation documents and launch information let ACUSTIQ build richer product records and visualizer choices.</p></div><a href="/for-matt">Contribute manufacturer assets <ArrowRight/></a></section>
</main></div>}
