import React from 'react';
import {ArrowRight, Building2, CheckCircle2, MapPin, PanelsTopLeft, Ruler, ShieldCheck, Wrench} from 'lucide-react';
import './regional.css';

export const regionalCities = [
  ['vancouver','Vancouver','Commercial interiors, tenant improvements, offices, retail and institutional ceiling work across Vancouver.'],
  ['burnaby','Burnaby','Office, institutional, mixed-use and commercial ceiling installations throughout Burnaby.'],
  ['surrey','Surrey','Commercial, institutional and growing mixed-use ceiling projects across Surrey.'],
  ['richmond','Richmond','Commercial, hospitality, retail and light-industrial ceiling work throughout Richmond.'],
  ['coquitlam','Coquitlam','Commercial, strata, institutional and tenant-improvement ceiling work in Coquitlam.'],
  ['langley','Langley','Commercial, retail, industrial-office and tenant-improvement ceiling installations in Langley.'],
  ['delta','Delta','Commercial, industrial-office and institutional ceiling systems across Delta.'],
  ['north-vancouver','North Vancouver','Commercial, hospitality, institutional and architectural ceiling work on the North Shore.'],
  ['west-vancouver','West Vancouver','Architectural, commercial and high-finish ceiling applications in West Vancouver.'],
  ['new-westminster','New Westminster','Commercial, institutional, office and renovation ceiling work in New Westminster.'],
  ['port-moody','Port Moody','Commercial, mixed-use and tenant-improvement ceiling installations in Port Moody.'],
  ['port-coquitlam','Port Coquitlam','Commercial, industrial-office and tenant-improvement ceiling systems in Port Coquitlam.'],
  ['maple-ridge','Maple Ridge','Commercial, institutional and mixed-use ceiling work throughout Maple Ridge.'],
  ['white-rock','White Rock','Commercial, hospitality and high-finish ceiling applications in White Rock.'],
  ['abbotsford','Abbotsford','Commercial, institutional, retail and industrial-office ceiling systems in Abbotsford.'],
  ['pitt-meadows','Pitt Meadows','Commercial and light-industrial ceiling installations in Pitt Meadows.'],
  ['tsawwassen','Tsawwassen','Retail, commercial, hospitality and tenant-improvement ceiling work in Tsawwassen.'],
  ['ladner','Ladner','Commercial, community and tenant-improvement ceiling systems in Ladner.'],
  ['ubc','UBC','Academic, institutional, research and commercial ceiling applications around the UBC campus.'],
  ['lower-mainland','Lower Mainland','Regional ceiling-system installation coverage connecting Metro Vancouver communities and the Fraser Valley.']
] as const;

const photos=['/projects/linear-wood-feature-ceiling.webp','/projects/cloud-ceiling-finished.webp','/projects/cloud-ceiling-installation-real.webp'];

export function RegionalInstallerPage({slug}:{slug:string}){
 const city=regionalCities.find(x=>x[0]===slug); if(!city)return null; const [,name,intro]=city;
 const ramboCityUrl=`https://rambowalls.com/locations/${slug}?utm_source=acustiq&utm_medium=referral&utm_campaign=${slug}-ceiling-installation`;
 return <main className="regional-page">
  <section className="regional-hero"><div><span>ACUSTIQ REGIONAL INSTALLER NETWORK · BRITISH COLUMBIA</span><h1>Ceiling Installers in {name}</h1><p>{intro} ACUSTIQ connects ceiling-system education with a regional installation path for suspended T-bar, acoustic, cloud, linear and specialty ceiling assemblies.</p><div className="regional-actions"><a href={ramboCityUrl}>Get {name} installation pricing <ArrowRight/></a><a href="tel:+17787732790">Call 778-773-2790</a><a href="/systems">Explore ceiling systems</a></div></div><img src={photos[0]} alt={`Architectural ceiling installation style available for ${name} projects`}/></section>
  <section className="featured-installer"><div className="featured-kicker"><MapPin/><span>FEATURED REGIONAL INSTALLER · LOWER MAINLAND</span></div><div className="featured-grid"><div><h2>Rambo Walls & Ceilings</h2><p>ACUSTIQ's featured regional installation partner for the Lower Mainland. The installation path is kept separate from neutral system education: use ACUSTIQ to understand ceiling options, then connect with Rambo Walls & Ceilings when a project needs field pricing, coordination and installation.</p><div className="installer-tags"><b>Suspended T-Bar</b><b>Acoustic Ceilings</b><b>Feature Ceilings</b><b>Steel Stud + Drywall Coordination</b><b>Tenant Improvements</b></div></div><div className="installer-card"><Building2/><span>SERVING</span><strong>{name}</strong><small>Lower Mainland / Metro Vancouver region</small><a href={ramboCityUrl}>Rambo Walls & Ceilings in {name} <ArrowRight/></a></div></div></section>
  <section className="regional-systems"><div className="regional-heading"><span>CEILING SYSTEMS</span><h2>From standard grid to architectural features.</h2><p>System selection depends on the room, acoustic target, access requirements, service coordination, appearance, budget and applicable project requirements — not the city name. These regional pages therefore connect local installation intent to ACUSTIQ's deeper system guidance.</p></div><div className="regional-cards"><a href="/systems/suspended-tbar"><PanelsTopLeft/><h3>Suspended T-Bar</h3><p>Accessible commercial ceiling grid with lay-in or tegular panel options.</p></a><a href="/systems/acoustic-clouds"><ShieldCheck/><h3>Acoustic Clouds</h3><p>Suspended absorptive elements for targeted reverberation control and visual definition.</p></a><a href="/systems/linear-wood"><Ruler/><h3>Linear Wood</h3><p>Architectural slat and plank systems with finish, access and acoustic considerations.</p></a><a href="/systems/specialty"><Wrench/><h3>Specialty Ceilings</h3><p>Custom forms, islands, integrated lighting and multi-trade ceiling assemblies.</p></a></div></section>
  <section className="regional-proof"><div><img src={photos[1]} alt="Finished suspended cloud ceiling with integrated lighting"/><span>FINISHED SYSTEM STYLE</span></div><div><img src={photos[2]} alt="Cloud ceiling framing and installation detail"/><span>INSTALLATION DETAIL</span></div><article><span>REAL INSTALLATION PHOTOGRAPHY</span><h2>See how ceiling ideas become field assemblies.</h2><p>These images are used as system and installation examples. Project addresses, companies, manufacturers and product claims are intentionally not invented; verified project information can be added later as structured project records.</p><a href="/#gallery">View installation gallery <ArrowRight/></a></article></section>
  <section className="regional-process"><span>LOCAL PROJECT PATH</span><h2>Understand it. Coordinate it. Install it.</h2><div><p><b>01</b><strong>Choose a system family</strong>Start with performance, appearance, access and application requirements.</p><p><b>02</b><strong>Develop the ceiling plane</strong>Coordinate grid direction, borders, clouds, lights, HVAC, sprinklers and access.</p><p><b>03</b><strong>Check technical requirements</strong>Use manufacturer-verified data and project-specific design requirements where applicable.</p><p><b>04</b><strong>Price + install locally</strong>Connect the concept to Rambo Walls & Ceilings as ACUSTIQ's featured Lower Mainland installer.</p></div></section>
  <section className="regional-faq"><div><span>{name.toUpperCase()} CEILING INSTALLATION</span><h2>Useful questions before pricing.</h2></div><div><details open><summary>What ceiling systems can be considered for a {name} project?</summary><p>Common options include suspended T-bar systems, acoustic panels, clouds, baffles, linear ceilings and specialty assemblies. The appropriate system depends on the specific project requirements and manufacturer documentation.</p></details><details><summary>Can lighting and mechanical services be coordinated with the ceiling?</summary><p>Yes. Reflected ceiling planning should account for fixtures, diffusers, sprinklers, access panels and other services before installation wherever possible.</p></details><details><summary>Who is ACUSTIQ's featured installer for {name}?</summary><p>Rambo Walls & Ceilings is presented by ACUSTIQ as its featured regional installer for the Lower Mainland, including {name}.</p></details><details><summary>Does ACUSTIQ replace project-specific design or engineering?</summary><p>No. ACUSTIQ provides system education and product information. Project-specific code, engineering, seismic, fire, acoustic and specification requirements should be confirmed by the appropriate project professionals and verified manufacturer documentation.</p></details></div></section>
  <section className="regional-nearby"><span>LOWER MAINLAND INSTALLER AREAS</span><h2>Explore nearby ceiling installer pages.</h2><div>{regionalCities.filter(x=>x[0]!==slug).slice(0,10).map(([s,n])=><a key={s} href={`/installers/${s}`}>{n}<ArrowRight/></a>)}</div></section>
  <section className="regional-cta"><CheckCircle2/><div><span>FEATURED REGIONAL INSTALLER</span><h2>Planning ceiling work in {name}?</h2><p>Explore the system on ACUSTIQ, then connect with Rambo Walls & Ceilings for Lower Mainland installation.</p></div><div className="regional-actions"><a href={ramboCityUrl}>Request project pricing <ArrowRight/></a><a href="sms:+17787732790">Text Rambo</a></div></section>
 </main>
}
