import React from 'react';
import {ArrowRight, Building2, FileText, Grid3X3, Ruler, ShieldCheck, Volume2} from 'lucide-react';
import './technical-library.css';

const topics=[
 {id:'acoustics',kicker:'01 / ACOUSTIC RATINGS',title:'NRC, CAC & STC Explained',Icon:Volume2},
 {id:'components',kicker:'02 / COMPONENTS',title:'Suspended Ceiling Components',Icon:Grid3X3},
 {id:'seismic',kicker:'03 / SEISMIC',title:'Seismic Ceiling Fundamentals',Icon:ShieldCheck},
 {id:'estimating',kicker:'04 / ESTIMATING',title:'Ceiling Takeoff & Estimating',Icon:Ruler},
 {id:'coordination',kicker:'05 / COORDINATION',title:'Lighting / HVAC / Sprinklers',Icon:Building2},
 {id:'specification',kicker:'06 / SPECIFICATION',title:'NMS / Specification Framework',Icon:FileText},
];

export default function TechnicalLibraryPage(){return <div className="tl-page">
<header className="tl-top"><a className="tl-brand" href="/">ACUSTIQ<span>.</span></a><nav><a href="/systems">Systems</a><a href="/visualizer">Visualizer</a><a href="/product-knowledge">Product Knowledge</a><a href="/technical-library">Technical Library</a><a href="/#gallery">Gallery</a></nav><a className="tl-price" href="/installers/vancouver">Get Installation Pricing</a></header>
<main>
<section className="tl-hero"><span>TECHNICAL LIBRARY</span><h1>Practical architectural<br/>ceiling knowledge.</h1><p>Field-useful guidance for architects, designers, estimators and installers covering acoustics, suspension systems, seismic concepts, takeoffs, coordination and Canadian specification language.</p><div className="tl-jump">{topics.map(({id,title,Icon})=><a href={`#${id}`} key={id}><Icon size={18}/><span>{title}</span></a>)}</div></section>

<section id="acoustics" className="tl-section"><div className="tl-heading"><span>01 / ACOUSTIC RATINGS</span><h2>NRC, CAC & STC Explained</h2><p>These three ratings get used interchangeably in the field, but they measure three completely different things. Specifying the wrong one is one of the most common reasons a finished ceiling does not perform the way the drawings promised.</p></div><div className="tl-three"><article><h3>NRC — Noise Reduction Coefficient</h3><p>NRC measures <b>absorption</b>: how much sound a surface soaks up instead of reflecting back into the room. It is derived per ASTM C423 from absorption coefficients at 250, 500, 1000 and 2000 Hz. High NRC is what controls reverberation and echo within a space. It does not describe sound transmission to an adjacent room.</p></article><article><h3>CAC — Ceiling Attenuation Class</h3><p>CAC measures sound travelling <b>between two closed rooms through a shared plenum</b> — up through one ceiling, across above the partition, and down through the neighbouring ceiling. It is tested per ASTM E1414. CAC matters when partitions stop at the ceiling instead of running full height to the deck.</p></article><article><h3>STC — Sound Transmission Class</h3><p>STC measures <b>transmission loss through a partition assembly</b>, tested per ASTM E90 and rated per ASTM E413. It is the familiar rating used for walls and floor/ceiling assemblies. A ceiling panel has a CAC; a wall assembly has an STC.</p></article></div><aside className="tl-callout"><b>The trade-off:</b> a lightweight porous panel optimized for high NRC may provide lower CAC, while a dense panel that blocks plenum sound may reflect more sound into the room. Closed offices often need both absorption and privacy, so determine which problem is being solved before selecting a panel.</aside></section>

<section id="components" className="tl-section tl-dark"><div className="tl-heading"><span>02 / COMPONENTS</span><h2>Suspended Ceiling Components</h2><p>A standard exposed-grid T-bar ceiling is a small structural system hung below the building structure. Knowing each component makes coordination, takeoff and troubleshooting far easier.</p></div><div className="tl-list"><p><b>Main runners (main tees).</b> Primary load-carrying members running continuously across the space and transferring ceiling load to the hanger wires.</p><p><b>Cross tees.</b> Shorter members, commonly 4 ft and 2 ft, that connect to main tees to form 2×2 or 2×4 grid modules.</p><p><b>Wall angle / perimeter molding.</b> Perimeter trim fixed to the walls that supports grid and panel edges.</p><p><b>Hanger wire.</b> Galvanized wire connecting main runners to the building structure. This is what actually holds the ceiling plane up.</p><p><b>Panels / tiles.</b> Lay-in acoustical units in mineral fibre, fibreglass, metal or other materials. Edge detail must match the selected grid profile.</p><p><b>Clips, splices and accessories.</b> Cross-tee clips, main-runner splices, hold-downs and expansion accessories that keep the assembly aligned and secure.</p></div><div className="tl-load">PANELS <ArrowRight/> CROSS TEES <ArrowRight/> MAIN RUNNERS <ArrowRight/> HANGER WIRE <ArrowRight/> STRUCTURE</div><p className="tl-note">Heavy items such as large light fixtures or diffusers should respect the grid load path or receive independent support so the suspension system is not overloaded. Grid duty and fire rating must match the specified assembly.</p></section>

<section id="seismic" className="tl-section"><div className="tl-heading"><span>03 / SEISMIC</span><h2>Seismic Ceiling Fundamentals</h2><p>During an earthquake a suspended ceiling moves as a plane. Seismic detailing is intended to prevent grid separation, perimeter impact and falling panels or fixtures.</p></div><aside className="tl-warning"><b>Verify before you build.</b> Seismic requirements depend on the current National Building Code of Canada, the applicable provincial code, ASTM E580 and the project’s assigned seismic design category. The concepts below are intentionally non-prescriptive.</aside><div className="tl-two"><article><h3>Perimeter conditions</h3><p>Seismic details may require wider perimeter support, defined clearances, fixed and free edges, or approved perimeter clips so the ceiling can move without losing panel support.</p></article><article><h3>Lateral bracing</h3><p>Larger or heavier ceilings may require splay wires and compression posts at spacing determined by the applicable design requirements.</p></article><article><h3>Separation / expansion joints</h3><p>Large ceiling planes may need to be divided into independently detailed sections so one large mass does not move as a single uncontrolled field.</p></article><article><h3>MEP coordination</h3><p>Lights, diffusers and sprinkler drops need their own support and clearances where required so they can move with — or independently of — the ceiling.</p></article></div></section>

<section id="estimating" className="tl-section tl-dark"><div className="tl-heading"><span>04 / ESTIMATING</span><h2>Ceiling Takeoff & Estimating</h2><p>A ceiling takeoff turns a reflected ceiling plan into quantities that can be priced. Start with finished ceiling area by room or zone, then derive the components.</p></div><div className="tl-list"><p><b>Main runners and cross tees.</b> Quantities come from the grid module and orientation. A 2×2 module uses more cross-tee footage than a 2×4 module.</p><p><b>Panels.</b> Driven by area and module, then adjusted for yield, perimeter cuts, irregular geometry and penetrations.</p><p><b>Wall angle / perimeter molding.</b> The linear footage of the full room perimeter, including insets, bulkheads and columns.</p><p><b>Hanger wire.</b> Count is driven by spacing along the mains plus perimeter and splice requirements, multiplied by drop height.</p><p><b>Accessories.</b> Clips, splices, hold-downs, seismic components and trim at changes in plane.</p></div><div className="tl-two"><article><h3>Waste</h3><p>Perimeter cuts, angled walls and penetrations create offcuts. A waste allowance is necessary, with more complex rooms generally requiring more allowance than clean rectangular spaces.</p></article><article><h3>What flat area misses</h3><p>Soffits, bulkheads, changes in elevation, floating clouds, penetrations, access conditions and high ceilings can add significant material and labour beyond simple square-foot calculations.</p></article></div></section>

<section id="coordination" className="tl-section"><div className="tl-heading"><span>05 / COORDINATION</span><h2>Lighting / HVAC / Sprinklers</h2><p>The ceiling plane is shared real estate. The reflected ceiling plan is where lighting, mechanical and fire-protection either coordinate — or collide.</p></div><div className="tl-three"><article><h3>Lighting</h3><p>Recessed fixtures occupy full or partial grid modules and interrupt the panel field. Heavier fixtures generally require independent support to structure rather than relying on the ceiling grid.</p></article><article><h3>HVAC</h3><p>Supply diffusers and return grilles share the ceiling module and may need their own support and clearances. Their placement affects both the RCP and the acoustic area of the ceiling.</p></article><article><h3>Sprinklers</h3><p>Sprinkler heads require correct positioning, clearance and escutcheons. In seismic assemblies, drops require the movement and clearance called for by the applicable design.</p></article></div><aside className="tl-callout">Keep the grid load path intact, coordinate penetrations on the RCP so cuts remain clean and symmetrical, and resolve seismic support and clearances before field installation.</aside></section>

<section id="specification" className="tl-section tl-dark"><div className="tl-heading"><span>06 / SPECIFICATION</span><h2>NMS / Specification Framework</h2><p>Getting a ceiling system specified is how it gets built. In Canada, ceiling work is commonly written into project manuals using the National Master Specification structure and CSC/CSI MasterFormat numbering.</p></div><div className="tl-three"><article><h3>Part 1 — General</h3><p>References, submittals, quality assurance, delivery and handling, and environmental conditions.</p></article><article><h3>Part 2 — Products</h3><p>Panel type and acoustic performance, grid type and duty, fire classification, finishes and accessories.</p></article><article><h3>Part 3 — Execution</h3><p>Installation requirements, tolerances, cleanup and the applicable installation standards such as ASTM C636 and ASTM E580 where seismic requirements apply.</p></article></div><p className="tl-note">Acoustical ceilings are typically documented in Division 09 — Finishes, including sections such as 09 51 00 Acoustical Ceilings and 09 53 00 Acoustical Ceiling Suspension Assemblies. Product values used for design or specification should come from verified manufacturer documentation.</p></section>

<section className="tl-cta"><div><span>FROM KNOWLEDGE TO FIELD PRICING</span><h2>Need a ceiling system installed in the Lower Mainland?</h2><p>Use ACUSTIQ to understand and compare the system, then connect with the featured regional installer for pricing and field coordination.</p></div><a href="/installers/vancouver">Rambo Walls & Ceilings <ArrowRight/></a></section>
</main><footer className="tl-footer"><b>ACUSTIQ.</b><span>Architectural Ceiling Systems & Acoustic Design</span><a href="/guest-post">Guest post with us — $10</a></footer>
</div>}
