import React from 'react';
import {ArrowLeft, ArrowRight, Building2, Calculator, CheckCircle2, ImagePlus, Palette, PanelsTopLeft, Sparkles, Upload, WandSparkles} from 'lucide-react';
import './visualizer-page.css';

const systems=[{id:'wood',label:'Slat Wood',desc:'Linear slats, warm finishes, directional rhythm'},{id:'clouds',label:'Acoustic Clouds',desc:'Suspended shapes for acoustic control and visual focus'},{id:'tbar',label:'T-Bar',desc:'Commercial grid and panel ceiling systems'},{id:'baffles',label:'Baffles',desc:'Vertical acoustic elements for open-plenum spaces'}];
const finishes:Record<string,string[]>={wood:['Natural Oak','White Oak','Walnut','Black','Light Maple','Custom Finish'],clouds:['White','Black','Charcoal','Warm Grey','Sand','Custom Colour'],tbar:['White Grid','Black Grid','Warm White Panel','Grey Panel','Black Panel','Custom'],baffles:['White','Black','Grey','Oak Look','Walnut Look','Custom Colour']};
const extras=['Pot lights','Linear lighting','LED / rope / cove lighting','Pendant lights','Supply diffusers','Return-air grilles','Sprinklers','Speakers','Smoke detectors','Access panels'];

export default function VisualizerPage(){
 const [photo,setPhoto]=React.useState(''); const [system,setSystem]=React.useState('wood'); const [finish,setFinish]=React.useState(finishes.wood[0]);
 const [length,setLength]=React.useState(24); const [width,setWidth]=React.useState(18); const [spacing,setSpacing]=React.useState(6); const [cloudL,setCloudL]=React.useState(8); const [cloudW,setCloudW]=React.useState(4); const [cloudQty,setCloudQty]=React.useState(3); const [selected,setSelected]=React.useState<Record<string,boolean>>({}); const [counts,setCounts]=React.useState<Record<string,number>>({});
 const area=Math.max(0,length*width), perimeter=Math.max(0,2*(length+width));
 const slatLF=Math.ceil(width*(length*12/Math.max(1,spacing))); const baffleLF=Math.ceil(width*(length*12/Math.max(1,spacing))); const cloudSF=cloudL*cloudW*cloudQty; const tileCount=Math.ceil(area/4*1.08);
 function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(file)setPhoto(URL.createObjectURL(file));}
 function chooseSystem(id:string){setSystem(id);setFinish(finishes[id][0]);}
 function toggle(x:string){setSelected(s=>({...s,[x]:!s[x]}));setCounts(c=>({...c,[x]:c[x]||1}));}
 const qty=system==='wood'?`${slatLF.toLocaleString()} LF slat run`:system==='clouds'?`${cloudSF.toLocaleString()} SF clouds`:system==='tbar'?`${tileCount.toLocaleString()} approx. 2×2 panels`:`${baffleLF.toLocaleString()} LF baffle run`;
 return <div className="vp-shell">
  <header className="vp-top"><a href="/"><b>ACUSTIQ<span>.</span></b></a><nav><a href="/systems">Systems</a><a href="/products">Products</a><a href="/technical-library">Technical Library</a></nav><a className="vp-back" href="/"><ArrowLeft/> Back to ACUSTIQ</a></header>
  <section className="vp-hero"><div><span>ROOM PHOTO + ARCHITECTURAL CEILING VISUALIZER</span><h1>Load your room.<br/><em>Try your ceiling.</em></h1><p>Upload a room photo, choose an architectural ceiling style, explore colours and finishes, coordinate the things that share the ceiling plane, then build a quantity summary that can eventually flow into Estimators.io.</p></div><div className="vp-flow"><div><b>01</b><ImagePlus/><strong>Upload room photo</strong><small>Use your own space as the visual starting point.</small></div><div><b>02</b><PanelsTopLeft/><strong>Choose ceiling style</strong><small>Slat wood, clouds, T-bar, baffles and more.</small></div><div><b>03</b><Palette/><strong>Add finishes + services</strong><small>Colours, lights, diffusers, sprinklers and accessories.</small></div><div><b>04</b><Calculator/><strong>Calculate + match</strong><small>Build quantities, product matches and estimating handoff.</small></div></div></section>
  <section className="vp-workspace"><aside className="vp-controls">
   <div className="vp-control-block"><span>1 / ROOM PHOTO</span><label className="vp-upload"><Upload/><b>{photo?'Change room photo':'Upload your room photo'}</b><small>JPG, PNG or WebP · preview stays in your browser</small><input type="file" accept="image/*" onChange={upload}/></label></div>
   <div className="vp-control-block"><span>2 / ROOM SIZE</span><div className="vp-dims"><label>Length (ft)<input type="number" min="1" value={length} onChange={e=>setLength(+e.target.value)}/></label><label>Width (ft)<input type="number" min="1" value={width} onChange={e=>setWidth(+e.target.value)}/></label></div><small className="vp-metric">{area.toLocaleString()} SF · {perimeter.toLocaleString()} LF perimeter</small></div>
   <div className="vp-control-block"><span>3 / CEILING STYLE</span><div className="vp-system-list">{systems.map(s=><button className={system===s.id?'active':''} onClick={()=>chooseSystem(s.id)} key={s.id}><b>{s.label}</b><small>{s.desc}</small></button>)}</div></div>
   <div className="vp-control-block"><span>4 / COLOUR + FINISH</span><div className="vp-finish-list">{finishes[system].map(f=><button className={finish===f?'active':''} onClick={()=>setFinish(f)} key={f}>{f}</button>)}</div></div>
   <div className="vp-control-block"><span>5 / QUICK CALCULATOR</span>{system==='clouds'?<div className="vp-dims"><label>Cloud L (ft)<input type="number" min="1" value={cloudL} onChange={e=>setCloudL(+e.target.value)}/></label><label>Cloud W (ft)<input type="number" min="1" value={cloudW} onChange={e=>setCloudW(+e.target.value)}/></label><label>Quantity<input type="number" min="1" value={cloudQty} onChange={e=>setCloudQty(+e.target.value)}/></label></div>:<label className="vp-single-input">Approx. spacing (in)<input type="number" min="1" value={spacing} onChange={e=>setSpacing(+e.target.value)}/></label>}<strong className="vp-calc-result">{qty}</strong><small className="vp-metric">Concept quantity only — verify against the selected manufacturer's system and project requirements.</small></div>
  </aside>
  <div className="vp-preview"><div className="vp-preview-bar"><span>CONCEPT PREVIEW</span><b>{systems.find(s=>s.id===system)?.label} · {finish}</b></div><div className={`vp-room vp-${system}`} style={photo?{backgroundImage:`linear-gradient(rgba(9,15,13,.08),rgba(9,15,13,.08)),url(${photo})`}:undefined}>{!photo&&<div className="vp-empty"><ImagePlus/><h2>Upload a room photo to start.</h2><p>Your photo becomes the base for ceiling-style and finish exploration.</p></div>}{photo&&<div className="vp-ceiling-demo"><span>{systems.find(s=>s.id===system)?.label}</span><strong>{finish}</strong><small>{area} SF room · {qty}</small></div>}</div>
   <section className="vp-extras"><div><span>DO YOU ALSO NEED?</span><h2>Coordinate the ceiling plane.</h2><p>Check anything that belongs in or around this ceiling. Add a rough count or linear-foot quantity now; detailed takeoff and pricing can be handed to the estimating layer later.</p></div><div className="vp-extra-grid">{extras.map(x=><div className={selected[x]?'selected':''} key={x}><button onClick={()=>toggle(x)} aria-pressed={!!selected[x]}><i>{selected[x]?'✓':''}</i><b>{x}</b></button>{selected[x]&&<label>Qty<input type="number" min="0" value={counts[x]||1} onChange={e=>setCounts(c=>({...c,[x]:+e.target.value}))}/></label>}</div>)}</div></section>
  </div></section>
  <section className="vp-summary"><div className="vp-section-head"><div><span>LIVE PROJECT SUMMARY</span><h2>One ceiling concept. Structured quantities.</h2></div><p>Selections are kept as useful project data rather than only a rendered image. That creates the bridge from inspiration into manufacturer matching, installer pricing and a future Estimators.io takeoff workflow.</p></div><div className="vp-summary-grid"><div><span>ROOM</span><strong>{length}' × {width}'</strong><b>{area.toLocaleString()} SF</b><small>{perimeter.toLocaleString()} LF perimeter</small></div><div><span>CEILING</span><strong>{systems.find(s=>s.id===system)?.label}</strong><b>{finish}</b><small>{qty}</small></div><div className="vp-summary-extras"><span>COORDINATION ITEMS</span>{Object.keys(selected).filter(x=>selected[x]).length?Object.keys(selected).filter(x=>selected[x]).map(x=><p key={x}><b>{x}</b><strong>{counts[x]||1}</strong></p>):<small>No additional items selected yet.</small>}</div><div className="vp-estimator-card"><Calculator/><span>ESTIMATING HANDOFF</span><h3>Send structured quantities to Estimators.io</h3><p>Room dimensions, ceiling system, finish, calculated quantities and selected coordination items are ready to become an estimating payload when the integration is connected.</p><a href="https://estimators.io/">Continue to Estimators.io <ArrowRight/></a></div></div></section>
  <section id="product-matches" className="vp-products"><div className="vp-section-head"><div><span>REAL PRODUCT MATCHING</span><h2>Design first. Manufacturer products second.</h2></div><p>Once a look is chosen, ACUSTIQ can map it to real manufacturer products using verified finish libraries, dimensions, system compatibility and technical documents.</p></div><div className="vp-product-grid"><div><b>YOUR DESIGN</b><h3>{systems.find(s=>s.id===system)?.label}</h3><p>{finish}</p><small>{qty}</small></div><div className="vp-placeholder-product"><Building2/><span>MANUFACTURER PRODUCT MATCH</span><h3>Product library opening</h3><p>Approved products, textures and finish assets will appear here when manufacturer libraries are connected.</p></div><div className="vp-placeholder-product"><Building2/><span>ALTERNATIVE MATCH</span><h3>Compare equivalent products</h3><p>Compare similar systems and finishes across participating manufacturers.</p></div></div></section>
  <section className="vp-manufacturer"><div><span>FOR MANUFACTURERS</span><h2>Add your products to the visualizer.</h2><p>Give ACUSTIQ approved product renders, finish swatches, seamless textures, dimensions, technical data and product links. We organize them into customer-friendly visual choices and connect those choices back to real product records.</p></div><div className="vp-manufacturer-list"><p><CheckCircle2/> Product families + system type</p><p><CheckCircle2/> Approved room/product renders</p><p><CheckCircle2/> Finish colours + textures</p><p><CheckCircle2/> Dimensions + configuration options</p><p><CheckCircle2/> CAD / BIM / technical PDFs</p><p><CheckCircle2/> Product URLs + launch updates</p><a href="/for-matt">Add manufacturer products <ArrowRight/></a></div></section>
  <section className="vp-installer"><div><span>LOWER MAINLAND INSTALLATION</span><h2>Like the design? Build it.</h2><p>Lower Mainland users can move from ACUSTIQ product exploration to field pricing and installation through Rambo Walls & Ceilings, ACUSTIQ's featured regional installer.</p></div><a href="https://rambowalls.com/">Contact regional installer <ArrowRight/></a></section>
 </div>;
}